name = "signature-cleaner"
main = "src/worker.js"
compatibility_date = "2023-10-12"
compatibility_flags = ["nodejs_compat"]

# Production KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "064faca259034a87a8efafad7e1718e5"

# Production R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "signature-images"

# Environment Variables (non-sensitive)
[vars]
# Add any non-sensitive environment variables here
# Sensitive variables like API keys should be set with: wrangler secret put

# Secrets (set these with wrangler secret put):
# GEMINI_API_KEY - Your Google Gemini API key
# JWT_SECRET - Secret key for JWT token signing